---
image: nixos/unstable
arch: null # aarch64 emulation available for "debian/unstable"
shell: true
oauth: ''
secrets:
  - 11097f83-8e5a-46c9-be7f-d4c746730000 # ~/.ssh/config
  - 47b60264-ce7e-46c6-a041-286c4346d2a2 # ~/.ssh/id_rsa
  - 20509cc9-2877-478f-8e59-4cde913ff21c # README access token
sources: []
repositories: {}
packages:
  - nixos.cachix
  - nixos.nixUnstable
environment:
  BUILD_SUBMITTER: git.sr.ht
  NIX: nix -vv --print-build-logs
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    accept-flake-config = true
    keep-going = true
    allow-import-from-derivation = true
artifacts: []
tasks:
  - show: |
      cd kasa.el
      $NIX --print-build-logs flake show
  - check: |
      cd kasa.el
      $NIX --print-build-logs flake check
  - readme: |
      cd kasa.el
      echo "Updating README"
      $NIX --print-build-logs develop .#devShells.x86_64-linux.default -c update-readme
      echo "Updated README"
  - mirror-to-github: |
      cd kasa.el
      git remote add github git@github.com:connorfeeley/kasa.el.git
      git push --prune github +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
triggers:
  - action: email
    condition: failure
    to: builds@git.cfeeley.org
