#+title: README
#+author: Connor Feeley
#+date: 2022-12-11

* ~kasa.el~
This package provides an interface between Emacs and the [[https://github.com/python-kasa/python-kasa][python-kasa]] library for controlling TP-Link Kasa smart home devices.

** Future Work
*** STRT Rough Implementation Notes
- Query python package for available devices
- Have a function to interactively select which device and plug to:
  + Toggle
  + Enable
  + Disable
  + Power cycle
- Allow configuring a default target:
    #+begin_src emacs-lisp
    (defvar kasa-default-target
    '("192.168.0.240" . "Ultrix-2NS")
    "Default power bar and plug to act on: (BAR . PLUG)")
    #+end_src
  + My personal ~pwrbar~ script:
      #+begin_src shell
      kasa --host 192.168.0.240 --type strip $POWER --name "Ultrix-2NS"
      #+end_src
- Should have a ~kasa-power-cycle-default~ interactive function which power cycles the ~kasa-default-target~

** License
#+begin_quote
MIT License

Copyright (c) 2022 Connor Feeley

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#+end_quote

* Homepage
/Note: this repository is mirrored to [[https://github.com/connorfeeley/kasa.el][GitHub]], though the canonical location is on [[https://sr.ht/~cfeeley/kasa.el/][Sourcehut]]./
